// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use itertools::Itertools;

use crate::context::GraphQLContext;
use crate::schema::*;
use diesel::prelude::*;
use serde::Deserialize;

#[derive(Queryable, Debug, Identifiable)]
pub struct Item {
    pub id: i32,
    pub title: String,
    pub body: String,
    pub done: bool,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct User {
    pub id: i32,
    pub username: String,
}

#[derive(Queryable, Debug, Identifiable, Insertable)]
#[diesel(primary_key(user_id, item_id))]
pub struct Vote {
    pub user_id: i32,
    pub item_id: i32,
    pub ordinal: i32,
}

use crate::schema::items::dsl::{done as item_done, items as all_items};
use crate::schema::users::dsl::{username as users_uname, users as all_users};
use crate::schema::votes::dsl::{item_id, ordinal, user_id, votes as all_votes};

#[derive(Deserialize)]
pub struct Ballot {
    pub votes: Vec<i32>,
}

#[derive(Queryable, Insertable)]
#[diesel(table_name = crate::schema::users)]
pub struct NewUser {
    pub username: String,
}

impl NewUser {
    pub fn login(self, context: &GraphQLContext) -> User {
        let mut conn = context.pool.get().expect("Could not get connection");

        // ensure that the user exists
        let _ = diesel::insert_into(crate::schema::users::table)
            .values(&self)
            .execute(&mut conn);

        users::table
            .filter(users::username.eq(&self.username))
            .get_result::<User>(&mut conn)
            .unwrap()
    }
}

impl Item {
    pub fn for_user(uid: i32, context: &GraphQLContext) -> Vec<(Item, Option<i32>)> {
        let mut conn = context.pool.get().expect("Could not get connection");

        all_items
            .left_join(crate::schema::votes::table.on(user_id.eq(&uid).and(item_id.eq(items::id))))
            .filter(crate::schema::items::done.eq(false))
            .order((user_id.desc(), ordinal.asc()))
            .select((crate::schema::items::all_columns, ordinal.nullable()))
            .load::<(Item, Option<i32>)>(&mut conn)
            .unwrap()
    }
}

impl Vote {
    pub fn run_election(context: &GraphQLContext) -> Option<Item> {
        let mut conn = context.pool.get().expect("Could not get connection");

        let votes: Vec<Vote> = all_votes
            .inner_join(items::table)
            .filter(item_done.eq(false))
            .order((user_id.asc(), ordinal.asc()))
            .select((user_id, item_id, ordinal))
            .load::<Vote>(&mut conn)
            .unwrap();

        // the extra collections here are sad.
        let votes: Vec<Vec<_>> = votes
            .into_iter()
            .group_by(|v| v.user_id)
            .into_iter()
            .map(|(_, ballot)| ballot.into_iter().map(|v| v.item_id).collect())
            .collect();

        match rcir::run_election(&votes, rcir::MajorityMode::RemainingMajority).ok()? {
            rcir::ElectionResult::Winner(&iid) => {
                Some(all_items.find(iid).get_result::<Item>(&mut conn).unwrap())
            }
            rcir::ElectionResult::Tie(iids) => {
                // TODO: maybe pick the oldest one?
                Some(
                    all_items
                        .find(*iids[0])
                        .get_result::<Item>(&mut conn)
                        .unwrap(),
                )
            }
        }
    }

    pub fn run_second_election(context: &GraphQLContext, winner: &Option<Item>) -> Option<Item> {
        let mut conn = context.pool.get().expect("Could not get connection");
        let winner = winner.as_ref()?;

        let votes = all_votes
            .inner_join(items::table)
            .filter(item_done.eq(false))
            .filter(item_id.ne(winner.id))
            .order((user_id.asc(), ordinal.asc()))
            .select((user_id, item_id, ordinal))
            .get_results::<Vote>(&mut conn)
            .unwrap();

        // the extra collections here are sad.
        let votes: Vec<Vec<_>> = votes
            .into_iter()
            .group_by(|v| v.user_id)
            .into_iter()
            .map(|(_, ballot)| ballot.into_iter().map(|v| v.item_id).collect())
            .collect();

        match rcir::run_election(&votes, rcir::MajorityMode::RemainingMajority).ok()? {
            rcir::ElectionResult::Winner(&iid) => {
                Some(all_items.find(iid).get_result::<Item>(&mut conn).unwrap())
            }
            rcir::ElectionResult::Tie(iids) => {
                // TODO: maybe pick the oldest one?
                Some(
                    all_items
                        .find(*iids[0])
                        .get_result::<Item>(&mut conn)
                        .unwrap(),
                )
            }
        }
    }

    pub fn save_ballot(uid: i32, ballot: Ballot, context: &GraphQLContext) {
        let mut conn = context.pool.get().expect("Could not get connection");

        diesel::delete(all_votes.filter(user_id.eq(&uid)))
            .execute(&mut conn)
            .unwrap();

        for (i, iid) in ballot.votes.into_iter().enumerate() {
            diesel::insert_into(crate::schema::votes::table)
                .values(Vote {
                    user_id: uid,
                    item_id: iid,
                    ordinal: i as i32,
                })
                .execute(&mut conn)
                .unwrap();
        }
    }
}
